---
- name: Install and start the service
  hosts: all
  
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: yes
