---
- name: Install and start the service
  hosts: all
  become: yes

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Ensure nginx service is started and enabled
    ansible.builtin.systemd:
      name: nginx
      state: started
      enabled: yes
