---
- name: Automating Script using Ansible
  hosts: all
  become: yes

  tasks:
  - name: copy the script in remote location
    copy:
      src: /home/test/script.sh
      dest: /tmp/script.sh
      mode: '0755'

  - name: Run Script
    shell: /tmp/script.sh
